package leafAnalysis;

/*
 * This file is the EdgeView.java and will be used to show the redered edge in a
 * larger view that the other EdgeResults.java. @author Daniel Elstob @version 1.0
 * 23-04-2015
 */
public class EdgeView extends javax.swing.JInternalFrame {
    // Creates new form EdgeView
    public EdgeView() {
        super("Edges Rendered",
                true, //resizable
                true, //closable
                true, //maximizable
                true);//iconifiable
        setLocation(400, 0);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        renderedScrollPane = new javax.swing.JScrollPane();
        renderedEdges = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setTitle("Rendered Edges");
        setName(""); // NOI18N

        renderedScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        renderedEdges.setBackground(new java.awt.Color(255, 255, 255));
        renderedScrollPane.setViewportView(renderedEdges);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(renderedScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(renderedScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EdgeView().setVisible(true);
            }
        });
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel renderedEdges;
    private javax.swing.JScrollPane renderedScrollPane;
    // End of variables declaration//GEN-END:variables

}
