package leafAnalysis;

/*
 * This file is the LeafViewer.java that will show the chosen opened image.
 * @author Daniel Elstob @version 1.0 23-04-2015
 */
public class LeafViewer extends javax.swing.JInternalFrame {

    // Creates new form LeafViewer
    public LeafViewer() {
        super("Image viewer",
                true, //resizable
                true, //closable
                true, //maximizable
                true);//iconifiable
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageScrollPane = new javax.swing.JScrollPane();
        lblImage = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(300, 580));

        lblImage.setToolTipText("");
        lblImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImage.setPreferredSize(new java.awt.Dimension(300, 580));
        imageScrollPane.setViewportView(lblImage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LeafViewer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane imageScrollPane;
    public javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables
}
